version: "3"

services:
  llamaedge-llama31:
    image: hudzy/llamaedge:llama3.1-8b
    container_name: llamaedge-llama31
    ports:
      - 8081:8080
    restart: unless-stopped

  llamaedge-phi35mini:
    image: hudzy/llamaedge:phi3.5-mini
    container_name: llamaedge-phi35mini
    ports:
      - 8082:8080
    restart: unless-stopped
