version: "3"

services:
  llamaedge-llama32-1b:
    image: hudzy/llamaedge:llama3.2-1b
    container_name: llamaedge-llama32-1b
    ports:
      - 8079:8080
    restart: unless-stopped

  llamaedge-llama32-3b:
    image: hudzy/llamaedge:llama3.2-3b
    container_name: llamaedge-llama32-3b
    ports:
      - 8080:8080
    restart: unless-stopped

  llamaedge-llama31:
    image: hudzy/llamaedge:llama3.1-8b
    container_name: llamaedge-llama31
    ports:
      - 8081:8080
    restart: unless-stopped

  llamaedge-phi35mini:
    image: hudzy/llamaedge:phi3.5-mini
    container_name: llamaedge-phi35mini
    ports:
      - 8082:8080
    restart: unless-stopped
