name: llamaedge:phi3.5-mini

on:
  push:
    branches:
      - master
    paths:
      - docker/Dockerfile.phi3.5-mini
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hudzy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./Dockerfile.phi3.5-mini
          tags: hudzy/llamaedge:phi3.5-mini
          platforms: linux/amd64
          push: true
